name: multi job
run-name: "multi job - [${{ github.ref_name }}]"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:

  job1:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: step1
        run: echo Hello, world!

      - name: step2
        run: |
          echo "step2" | tee -a "$GITHUB_STEP_SUMMARY"

      - name: step3
        run: echo "step3"

      - name: step4
        run: echo "step4"

      - name: step5(on error)
        if: failure()
        run: echo "step5"

  error-handler:
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    needs: [job1]
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: handle error
        run: |
          echo "handle error" | tee -a "#GITHUB_OUTPUT"