name: PR
run-name: "PR comment - [${{ github.ref_name }}]"

on:
  workflow_dispatch:
    inputs:
      pr_number:
        required: true
        type: string

env:
  PR_NUMBER: ${{inputs.pr_number}}

permissions:
  contents: write
  pull-requests: write

jobs:
  write-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Write a comment
        uses: actions/github-script@v7
        with:
          result-encoding: string
          retries: 3
          script: |
            var arr1 = ['a', 'b', 'c'];
            var arr2 = ['1', '2', '3'];

            var errorMsg1 = arr1.map(x => `- \`${x}\``).join('\r\n');
            var errorMsg2 = arr2.map(x => `- \`${x}\``).join('\n');

            await github.rest.issues.createComment({
              issue_number: '${{env.PR_NUMBER}}',
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Error has occurred\r\n${errorMsg1}`
            });

            await github.rest.issues.createComment({
              issue_number: '${{env.PR_NUMBER}}',
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Error has occurred\r\n${errorMsg2}`
            });

            await github.rest.issues.createComment({
              issue_number: '${{env.PR_NUMBER}}',
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Error has occurred\n${errorMsg1}\r\n${errorMsg2}`
            });
