name: Sub Workflow

on:
  workflow_call:
    inputs:
      org-var:
        required: true
        type: string
      
      repo-var:
        required: true
        type: string

      env-var:
        required: true
        type: string

env:
  ORG_VAR: ${{ inputs.org-var }}
  REPO_VAR: ${{ inputs.repo-var }}
  ENV_VAR: ${{ inputs.env-var }}

jobs:

  job1:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Use env and vars
        run: |
          echo org-var (input)  '${{ inputs.org-var }}'
          echo org-var (global) '${{ vars.GPU_TYPE }}'
          echo env-var (input)  '${{ inputs.env-var }}'
          echo env-var (global) '${{ vars.ENV_VAR }}'
          echo repo-var (input)  '${{ inputs.repo-var }}'
          echo repo-var (global) '${{ vars.REPO_VAR1 }}'
